// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

/**
 * CommonUserTypes.h
 *
 * 定义 CommonUser 插件通用的枚举与结构体：在线上下文、用户初始化状态、
 * 权限（Privilege）、可用性（Availability）、权限结果、异步任务状态，
 * 以及统一的在线操作结果结构 FOnlineResultInformation。
 *
 * 注意：本文件里的 OSSv1 / OSSv2 分支由编译宏 COMMONUSER_OSSV1 控制，
 * 该宏在 CommonUser.Build.cs 中由 bUseOnlineSubsystemV1 决定。
 */

#if COMMONUSER_OSSV1

// Online Subsystem (OSS v1) includes and forward declares
#include "OnlineSubsystemTypes.h"
class IOnlineSubsystem;
struct FOnlineError;
using FOnlineErrorType = FOnlineError;
using ELoginStatusType = ELoginStatus::Type;

#else

// Online Services (OSS v2) includes and forward declares
#include "Online/Connectivity.h"
#include "Online/OnlineError.h"
namespace UE::Online
{
	enum class ELoginStatus : uint8;
	enum class EPrivilegeResults : uint32;
	enum class EUserPrivileges : uint8;
	using IAuthPtr = TSharedPtr<class IAuth>;
	using IOnlineServicesPtr = TSharedPtr<class IOnlineServices>;
	template <typename OpType>
	class TOnlineResult;
	struct FAuthLogin;
	struct FConnectionStatusChanged;
	struct FExternalUIShowLoginUI;
	struct FAuthLoginStatusChanged;
	struct FQueryUserPrivilege;
	struct FAccountInfo;
}
using FOnlineErrorType = UE::Online::FOnlineError;
using ELoginStatusType = UE::Online::ELoginStatus;

#endif

#include "CommonUserTypes.generated.h"


/** Enum specifying where and how to run online queries */
/**
 * 在线上下文：指明一次操作要作用于哪一套在线后端。
 * 大部分平台只有一套系统（Game 等价于 Service 或 Platform），
 * 主机平台才会区分“平台层账号”和“服务层账号”两套。
 */
UENUM(BlueprintType)
enum class ECommonUserOnlineContext : uint8
{
	// Game：游戏代码传入的默认上下文，会按平台规则解析/合并到具体系统
	/** Called from game code, this uses the default system but with special handling that could merge results from multiple contexts */
	Game,

	// Service 别名前的默认系统：一定存在，实际等于 Service 或 Platform 之一
	/** The default engine online system, this will always exist and will be the same as either Service or Platform */
	Default,
	
	// Service：明确指定外部服务系统，可能不存在
	/** Explicitly ask for the external service, which may not exist */
	Service,

	// ServiceOrDefault：优先服务系统，不存在则回退默认系统
	/** Looks for external service first, then falls back to default */
	ServiceOrDefault,
	
	// Platform：明确指定平台系统，可能不存在
	/** Explicitly ask for the platform system, which may not exist */
	Platform,

	// PlatformOrDefault：优先平台系统，不存在则回退默认系统
	/** Looks for platform system first, then falls back to default */
	PlatformOrDefault,

	// Invalid：无效上下文
	/** Invalid system */
	Invalid
};

/** Enum describing the state of initialization for a specific user */
/**
 * 本地用户初始化状态机。UI 通常轮询 GetLocalPlayerInitializationState，
 * 据此决定显示“请按 Start 键”、登录中，还是允许进入游戏。
 */
UENUM(BlueprintType)
enum class ECommonUserInitializationState : uint8
{
	// 尚未开始登录流程
	/** User has not started login process */
	Unknown,

	// 正在通过本地（平台层）登录获取用户身份
	/** Player is in the process of acquiring a user id with local login */
	DoingInitialLogin,

	// 本地已登录，正在进行网络（服务层）登录
	/** Player is performing the network login, they have already logged in locally */
	DoingNetworkLogin,

	// 登录彻底失败
	/** Player failed to log in at all */
	FailedtoLogin,

	
	// 已登录且拥有联机功能权限
	/** Player is logged in and has access to online functionality */
	LoggedInOnline,

	// 已本地登录（真实用户或访客），但无法进行联机操作
	/** Player is logged in locally (either guest or real user), but cannot perform online actions */
	LoggedInLocalOnly,


	// 无效状态或无效用户
	/** Invalid state or user */
	Invalid,
};

/** Enum specifying different privileges and capabilities available to a user */
/**
 * 用户权限/能力枚举：描述某项功能是否允许使用。
 * 游戏通常只关心 CanPlay（能玩）与 CanPlayOnline（能联机）。
 */
UENUM(BlueprintType)
enum class ECommonUserPrivilege : uint8
{
	// 是否可以进行游戏（单机或联机均可）
	/** Whether the user can play at all, online or offline */
	CanPlay,

	// 是否可以进行联机游戏
	/** Whether the user can play in online modes */
	CanPlayOnline,

	// 是否可以使用文字聊天
	/** Whether the user can use text chat */
	CanCommunicateViaTextOnline,

	// 是否可以使用语音聊天
	/** Whether the user can use voice chat */
	CanCommunicateViaVoiceOnline,

	// 是否可以访问其他用户生成的内容（UGC）
	/** Whether the user can access content generated by other users */
	CanUseUserGeneratedContent,

	// 是否可以参与跨平台联机
	/** Whether the user can ever participate in cross-play */
	CanUseCrossPlay,

	// 无效权限（同时兼作有效权限的数量）
	/** Invalid privilege (also the count of valid ones) */
	Invalid_Count					UMETA(Hidden)
};

/** Enum specifying the general availability of a feature or privilege, this combines information from multiple sources */
/**
 * 功能可用性：把“权限查询结果 + 当前用户状态”综合成一个给 UI 用的结论。
 */
UENUM(BlueprintType)
enum class ECommonUserAvailability : uint8
{
	// 完全未知，需要向平台查询
	/** State is completely unknown and needs to be queried */
	Unknown,

	// 当前完全可用
	/** This feature is fully available for use right now */
	NowAvailable,

	// 正常登录流程完成后可能变为可用
	/** This might be available after the completion of normal login procedures */
	PossiblyAvailable,

	// 当前不可用（例如断网），但将来可能恢复
	/** This feature is not available now because of something like network connectivity but may be available in the future */
	CurrentlyUnavailable,

	// 本次会话内永远不可用（账号或平台的硬性限制）
	/** This feature will never be available for the rest of this session due to hard account or platform restrictions */
	AlwaysUnavailable,

	// 无效功能
	/** Invalid feature */
	Invalid,
};

/** Enum giving specific reasons why a user may or may not use a certain privilege */
/**
 * 权限查询的原始结果：来自平台/服务返回的细粒度原因，可直接展示给玩家。
 */
UENUM(BlueprintType)
enum class ECommonUserPrivilegeResult : uint8
{
	// 状态未知，需要查询
	/** State is unknown and needs to be queried */
	Unknown,

	// 权限完全可用
	/** This privilege is fully available for use */
	Available,

	// 用户尚未完成登录
	/** User has not fully logged in */
	UserNotLoggedIn,

	// 用户未拥有该游戏或内容
	/** User does not own the game or content */
	LicenseInvalid,

	// 需要先更新或打补丁
	/** The game needs to be updated or patched before this will be available */
	VersionOutdated,

	// 没有网络连接，重连后可能恢复
	/** No network connection, this may be resolved by reconnecting */
	NetworkConnectionUnavailable,

	// 家长控制限制
	/** Parental control failure */
	AgeRestricted,

	// 账号缺少所需订阅或账号类型
	/** Account does not have a required subscription or account type */
	AccountTypeRestricted,

	// 其他账号/用户限制，例如被服务封禁
	/** Another account/user restriction such as being banned by the service */
	AccountUseRestricted,

	// 其他平台特定的失败原因
	/** Other platform-specific failure */
	PlatformFailure,
};

/** Used to track the progress of different asynchronous operations */
// 异步任务状态：登录流水线中每个子步骤（平台授权/自动登录/登录 UI/权限查询）的进度
enum class ECommonUserAsyncTaskState : uint8
{
	// 任务尚未启动
	/** The task has not been started */
	NotStarted,
	// 任务正在处理中
	/** The task is currently being processed */
	InProgress,
	// 任务已成功完成
	/** The task has completed successfully */
	Done,
	// 任务失败
	/** The task failed to complete */
	Failed
};

/** Detailed information about the online error. Effectively a wrapper for FOnlineError. */
/**
 * 统一的在线操作结果：把 OSSv1 的 FOnlineError 与 OSSv2 的 EOnlineServices 错误
 * 归一化成同一份结构，方便蓝图/UI 统一处理成功与失败。
 */
USTRUCT(BlueprintType)
struct FOnlineResultInformation
{
	GENERATED_BODY()

	// 操作是否成功；成功时下面的错误字段不含有效信息
	/** Whether the operation was successful or not. If it was successful, the error fields of this struct will not contain extra information. */
	UPROPERTY(BlueprintReadOnly)
	bool bWasSuccessful = true;

	// 唯一错误 ID，可用于与已知错误做精确比对
	/** The unique error id. Can be used to compare against specific handled errors. */
	UPROPERTY(BlueprintReadOnly)
	FString ErrorId;

	// 展示给玩家的错误文本
	/** Error text to display to the user. */
	UPROPERTY(BlueprintReadOnly)
	FText ErrorText;

	// 把当前版本在线层的错误结构转换成上面的通用字段（OSSv1 与 OSSv2 实现不同）
	/**
	 * Initialize this from an FOnlineErrorType
	 * @param InOnlineError the online error to initialize from
	 */
	void COMMONUSER_API FromOnlineError(const FOnlineErrorType& InOnlineError);
};
